version: "3"
services:
  web:
    build: .
    image: lamp-nginx
    tty: true
    ports:
    - "80:80"
    - "443:443"
    - "3306:3306"
    - "22:22"
    environment:
    - DEBIAN_FRONTEND=noninteractive
    - TZ=UTC
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    expose:
      - "80"
      - "443"
      - "3306"
      - "22"
    volumes:
      - ./certs:/certs:ro
      - ./www/site:/var/www/html/site:rw
      - ./conf/nginx/sites-enabled:/etc/nginx/sites-enabled:rw
      - ./conf/supervisor:/etc/supervisor/conf.d
      - ./data/mariadb:/var/lib/mysql
    networks:
      - app-network
#  db:
#    image: mariadb
#    tty: true
#    ports:
#    - "3306:3306"
#    environment:
#    - MYSQL_ROOT_PASSWORD=root
#    - MYSQL_USER=root
#    - TZ=Europe/Madrid
#    networks:
#      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge